basePath: /
info:
  contact: {}
  description: application description
  title: App
  version: "0.1"
paths:
  /:
    get:
      consumes:
      - application/json
      description: Home
      produces:
      - application/json
      responses: {}
      summary: ping example
      tags:
      - Home
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: User Login
      parameters:
      - description: Email
        in: path
        name: email
        required: true
        type: string
      - description: Password
        in: path
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: ping example
      tags:
      - Users
  /api/auth/logout:
    post:
      consumes:
      - application/json
      description: User Logout
      produces:
      - application/json
      responses: {}
      summary: ping example
      tags:
      - Users
  /api/auth/me:
    post:
      description: User
      produces:
      - application/json
      responses: {}
      summary: show User
      tags:
      - Users
  /api/auth/refresh:
    post:
      consumes:
      - application/json
      description: User Refresh
      produces:
      - application/json
      responses: {}
      summary: ping example
      tags:
      - Users
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: User Register
      produces:
      - application/json
      responses: {}
      summary: ping example
      tags:
      - Users
securityDefinitions:
  Token:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
